### PR TITLE
create copy of input data to allow manipulation

### PR DESCRIPTION
**Pull request by soumak77**
addressed issue introduced by https://github.com/personality-insights/sunburst-chart/pull/7#issuecomment-258885761

### CODE REVIEW

**Comment by germanattanasio** [comment]
For a complete copy, I would suggest you to use the `extend` module. I think that you are just copying the top level reference with this changes.

**Comment by soumak77** [comment]
It is true the rest of the code will be working with references to the original data, however, since none of the code manipulates the data, a deep copy can be avoided.  The changes made with this PR resolves the issues of modifying the `children` property of the input data (a copy is created by using the `filter` method).  None of the other properties of the input object appear to be used, so that is why I only found it necessary to create a shallow copy of the `children` array.

**Comment by soumak77** [comment]
@germanattanasio would it be possible to get a patch release published with these changes?

**Comment by germanattanasio** [comment]
done

**Comment by soumak77** [comment]
@germanattanasio the files in the [bin](https://github.com/personality-insights/sunburst-chart/tree/master/bin) directory were not updated

**Comment by germanattanasio** [comment]
done

**Pull request merged**
